/**
 * In-memory mock data served by the local Route Handlers in `src/app/api/v1`.
 * Replaces the (dead) mockapi.io backend. Ids cross-reference each other:
 * every company points to a real country/category, and promotions/sales
 * point to real companies — so the dashboard aggregates stay consistent.
 */
import {
    Category,
    Company,
    CompanyStatus,
    Country,
    Promotion,
    SummarySales,
} from './api';

export const countries: Country[] = [
    { id: '1', title: 'USA' },
    { id: '2', title: 'Germany' },
    { id: '3', title: 'Japan' },
    { id: '4', title: 'France' },
    { id: '5', title: 'Ukraine' },
    { id: '6', title: 'Brazil' },
];

export const categories: Category[] = [
    { id: '1', title: 'Products' },
    { id: '2', title: 'Services' },
    { id: '3', title: 'Logistics' },
    { id: '4', title: 'Finance' },
    { id: '5', title: 'Healthcare' },
    { id: '6', title: 'Education' },
    { id: '7', title: 'Retail' },
    { id: '8', title: 'Technology' },
];

export const companies: Company[] = [
    {
        id: '1',
        title: 'Costco',
        description:
            'Membership-only wholesale retailer selling bulk products at low prices.',
        status: CompanyStatus.Active,
        joinedDate: '2023-02-19',
        hasPromotions: true,
        categoryId: '1',
        categoryTitle: 'Products',
        countryId: '1',
        countryTitle: 'USA',
    },
    {
        id: '2',
        title: 'Siemens',
        description:
            'Industrial manufacturing company focused on automation and energy.',
        status: CompanyStatus.Active,
        joinedDate: '2022-06-04',
        hasPromotions: true,
        categoryId: '8',
        categoryTitle: 'Technology',
        countryId: '2',
        countryTitle: 'Germany',
    },
    {
        id: '3',
        title: 'Sony',
        description: 'Consumer electronics and entertainment corporation.',
        status: CompanyStatus.Active,
        joinedDate: '2024-11-23',
        hasPromotions: false,
        categoryId: '8',
        categoryTitle: 'Technology',
        countryId: '3',
        countryTitle: 'Japan',
    },
    {
        id: '4',
        title: 'Carrefour',
        description:
            'Multinational retail chain operating supermarkets and hypermarkets.',
        status: CompanyStatus.Pending,
        joinedDate: '2025-03-15',
        hasPromotions: true,
        categoryId: '7',
        categoryTitle: 'Retail',
        countryId: '4',
        countryTitle: 'France',
    },
    {
        id: '5',
        title: 'Nova Poshta',
        description: 'Logistics and express delivery service provider.',
        status: CompanyStatus.Active,
        joinedDate: '2024-09-30',
        hasPromotions: false,
        categoryId: '3',
        categoryTitle: 'Logistics',
        countryId: '5',
        countryTitle: 'Ukraine',
    },
    {
        id: '6',
        title: 'Embraer',
        description:
            'Aerospace company producing commercial and executive aircraft.',
        status: CompanyStatus.Suspended,
        joinedDate: '2021-01-12',
        hasPromotions: false,
        categoryId: '2',
        categoryTitle: 'Services',
        countryId: '6',
        countryTitle: 'Brazil',
    },
    {
        id: '7',
        title: 'Walmart',
        description:
            'Retail corporation running discount department and grocery stores.',
        status: CompanyStatus.Active,
        joinedDate: '2023-07-08',
        hasPromotions: true,
        categoryId: '7',
        categoryTitle: 'Retail',
        countryId: '1',
        countryTitle: 'USA',
    },
    {
        id: '8',
        title: 'Allianz',
        description:
            'Financial services group offering insurance and asset management.',
        status: CompanyStatus.NotActive,
        joinedDate: '2022-05-19',
        hasPromotions: false,
        categoryId: '4',
        categoryTitle: 'Finance',
        countryId: '2',
        countryTitle: 'Germany',
    },
    {
        id: '9',
        title: 'Toyota',
        description:
            'Automotive manufacturer producing cars and hybrid vehicles.',
        status: CompanyStatus.Active,
        joinedDate: '2024-10-02',
        hasPromotions: true,
        categoryId: '1',
        categoryTitle: 'Products',
        countryId: '3',
        countryTitle: 'Japan',
    },
    {
        id: '10',
        title: 'Sanofi',
        description:
            'Pharmaceutical company developing healthcare treatments and vaccines.',
        status: CompanyStatus.Pending,
        joinedDate: '2025-04-27',
        hasPromotions: false,
        categoryId: '5',
        categoryTitle: 'Healthcare',
        countryId: '4',
        countryTitle: 'France',
    },
    {
        id: '11',
        title: 'MonoBank',
        description: 'Digital-only bank providing mobile financial services.',
        status: CompanyStatus.Active,
        joinedDate: '2025-08-14',
        hasPromotions: true,
        categoryId: '4',
        categoryTitle: 'Finance',
        countryId: '5',
        countryTitle: 'Ukraine',
    },
    {
        id: '12',
        title: 'Coursera',
        description: 'Online education platform offering courses and degrees.',
        status: CompanyStatus.Active,
        joinedDate: '2023-12-01',
        hasPromotions: false,
        categoryId: '6',
        categoryTitle: 'Education',
        countryId: '1',
        countryTitle: 'USA',
    },
];

export const promotions: Promotion[] = [
    {
        id: '1',
        title: 'Winter Wholesale Sale',
        description: 'Seasonal discount on bulk household goods.',
        discount: 15,
        companyId: '1',
        companyTitle: 'Costco',
    },
    {
        id: '2',
        title: 'Smart Energy Bundle',
        description: 'Reduced pricing on automation equipment packages.',
        discount: 20,
        companyId: '2',
        companyTitle: 'Siemens',
    },
    {
        id: '3',
        title: 'Grocery Weekend Deal',
        description: 'Weekend-only savings on fresh groceries.',
        discount: 10,
        companyId: '4',
        companyTitle: 'Carrefour',
    },
    {
        id: '4',
        title: 'Back to School',
        description: 'Discounts on school supplies and electronics.',
        discount: 25,
        companyId: '7',
        companyTitle: 'Walmart',
    },
    {
        id: '5',
        title: 'Spring Drive Offer',
        description: 'Special pricing on selected hybrid models.',
        discount: 12,
        companyId: '9',
        companyTitle: 'Toyota',
    },
    {
        id: '6',
        title: 'Cashback Boost',
        description: 'Increased cashback on everyday card payments.',
        discount: 5,
        companyId: '11',
        companyTitle: 'MonoBank',
    },
];

export const summarySales: SummarySales[] = [
    {
        id: '1',
        companyId: '1',
        companyTitle: 'Costco',
        sold: 320,
        income: 48000,
    },
    {
        id: '2',
        companyId: '2',
        companyTitle: 'Siemens',
        sold: 145,
        income: 73000,
    },
    {
        id: '3',
        companyId: '7',
        companyTitle: 'Walmart',
        sold: 510,
        income: 61000,
    },
    {
        id: '4',
        companyId: '9',
        companyTitle: 'Toyota',
        sold: 88,
        income: 92000,
    },
    {
        id: '5',
        companyId: '11',
        companyTitle: 'MonoBank',
        sold: 230,
        income: 17500,
    },
    {
        id: '6',
        companyId: '3',
        companyTitle: 'Sony',
        sold: 175,
        income: 54000,
    },
];
